import { useEffect, useMemo, useState } from 'react'
import './FinancialCenter.css'

const money = value => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
const pct = (a,b) => b ? `${((a/b)*100).toFixed(1)}%` : '0%'
const fmt = value => value ? new Date(value).toLocaleString('pt-BR') : '—'
const label = s => ({approved:'Aprovado',paid:'Pago',pending:'Pendente',in_process:'Processando',failed:'Falhou',rejected:'Rejeitado',refunded:'Estornado',charged_back:'Chargeback'}[s] || s || '—')

export default function FinancialCenter({ request }) {
  const [dashboard,setDashboard] = useState(null); const [transactions,setTransactions] = useState(null); const [payouts,setPayouts] = useState(null); const [filters,setFilters] = useState({app_slug:'',provider:'',status:'',from:'',to:''}); const [selected,setSelected] = useState(null); const [error,setError] = useState(''); const [live,setLive] = useState(true)
  const qs = useMemo(() => new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString(),[filters])
  async function load(silent=false){ try { if(!silent)setError(''); const [d,t,p]=await Promise.all([request(`/admin/ecosystem/financial/dashboard?${qs}`),request(`/admin/ecosystem/financial/transactions?${qs}&per_page=100`),request('/admin/ecosystem/financial/payouts')]); setDashboard(d);setTransactions(t);setPayouts(p) } catch(e){setError(e.message)} }
  useEffect(()=>{load()},[qs])
  useEffect(()=>{if(!live)return; const id=setInterval(()=>load(true),10000); return()=>clearInterval(id)},[live,qs])
  async function inspect(id){try{setSelected((await request(`/admin/ecosystem/financial/transactions/${id}`)).transaction)}catch(e){setError(e.message)}}
  const s=dashboard?.summary||{}, total=Number(s.totals?.transactions||0), approved=Number(s.approved?.count||0), failed=Number(s.failed?.count||0)
  return <div className="finance-stack">
    <section className="finance-hero"><div><p>FINANCIAL OPERATIONS CENTER</p><h2>Saúde financeira do ecossistema</h2><span>Vendas, pagamentos, taxas, liquidação, falhas, estornos e repasses em uma única visão operacional.</span></div><div className="finance-live"><i className={live?'on':''}/><b>{live?'Tempo real ativo':'Tempo real pausado'}</b><button onClick={()=>setLive(v=>!v)}>{live?'Pausar':'Ativar'}</button></div></section>
    {error&&<div className="finance-alert critical"><b>Falha no monitoramento</b><span>{error}</span></div>}
    <div className="finance-kpis"><Kpi title="Volume bruto" value={money(s.totals?.gross)} sub={`${total} transações`} /><Kpi title="Receita da plataforma" value={money(s.totals?.platform_fees)} sub="taxas Peter Tecnet" /><Kpi title="Líquido vendedores" value={money(s.totals?.seller_net)} sub="a liquidar/liquidado" /><Kpi title="Aprovação" value={pct(approved,total)} sub={`${approved} aprovadas`} /><Kpi title="Falhas" value={pct(failed,total)} sub={`${failed} transações`} danger={failed>0} /><Kpi title="Estornos" value={money(s.refunded?.amount)} sub={`${s.refunded?.count||0} ocorrências`} danger={Number(s.refunded?.count)>0} /></div>
    <section className="finance-panel"><header><div><b>Central de alertas</b><small>Anomalias e situações que exigem atenção</small></div></header><div className="finance-alerts">{dashboard?.alerts?.length?dashboard.alerts.map((a,i)=><div className={`finance-alert ${a.severity}`} key={i}><b>{a.title}</b><span>{a.message}</span></div>):<div className="finance-alert ok"><b>Operação saudável</b><span>Nenhum alerta financeiro detectado no período.</span></div>}</div></section>
    <section className="finance-panel"><header><div><b>Filtros operacionais</b><small>Investigue o fluxo por aplicação, provedor, status e período</small></div><button onClick={()=>setFilters({app_slug:'',provider:'',status:'',from:'',to:''})}>Limpar</button></header><div className="finance-filters"><input placeholder="Aplicação (slug)" value={filters.app_slug} onChange={e=>setFilters({...filters,app_slug:e.target.value})}/><input placeholder="Provedor" value={filters.provider} onChange={e=>setFilters({...filters,provider:e.target.value})}/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option><option value="approved">Aprovado</option><option value="pending">Pendente</option><option value="failed">Falhou</option><option value="rejected">Rejeitado</option><option value="refunded">Estornado</option></select><input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></div></section>
    <div className="finance-grid"><section className="finance-panel"><header><div><b>Performance por aplicação</b><small>GMV, receita e líquido por produto</small></div></header><Table heads={['Aplicação','Transações','Bruto','Taxas','Líquido']} rows={dashboard?.applications?.map(x=>[x.application_name||x.app_slug,x.transactions,money(x.gross),money(x.platform_fees),money(x.seller_net)])}/></section><section className="finance-panel"><header><div><b>Gateways / provedores</b><small>Taxa de sucesso por infraestrutura de pagamento</small></div></header><Table heads={['Provedor','Tx','Aprov.','Falhas','Sucesso']} rows={dashboard?.providers?.map(x=>[x.provider,x.transactions,x.approved,x.failed,pct(x.approved,x.transactions)])}/></section></div>
    <section className="finance-panel"><header><div><b>Fluxo dos últimos 30 dias</b><small>Volume financeiro diário e receita da plataforma</small></div></header><div className="finance-chart">{dashboard?.timeline?.map(x=>{const max=Math.max(...dashboard.timeline.map(i=>Number(i.gross||0)),1);return <div className="finance-bar" key={x.day} title={`${x.day}: ${money(x.gross)}`}><span style={{height:`${Math.max(4,(Number(x.gross)/max)*100)}%`}}/><small>{String(x.day).slice(5)}</small></div>})}</div></section>
    <section className="finance-panel"><header><div><b>Transações</b><small>Trilha operacional completa dos pagamentos</small></div><strong>{transactions?.total||0} registros</strong></header><div className="finance-table-wrap"><table><thead><tr><th>Data</th><th>Aplicação</th><th>Provedor</th><th>Referência</th><th>Método</th><th>Status</th><th>Bruto</th><th>Taxa</th><th>Líquido</th></tr></thead><tbody>{transactions?.data?.map(t=><tr key={t.id} onClick={()=>inspect(t.id)}><td>{fmt(t.created_at)}</td><td>{t.application_name||t.app_slug}</td><td>{t.provider}</td><td>{t.source_reference}</td><td>{t.method||'—'}</td><td><span className={`finance-status ${t.status}`}>{label(t.status)}</span></td><td>{money(t.gross_amount)}</td><td>{money(t.platform_fee)}</td><td>{money(t.seller_net)}</td></tr>)}</tbody></table></div></section>
    <section className="finance-panel"><header><div><b>Repasses e saques</b><small>Solicitações de payout das aplicações</small></div><strong>{payouts?.summary?.pending||0} pendentes</strong></header><Table heads={['Criado','Status','Valor','Produção','Referência']} rows={payouts?.data?.map(x=>[fmt(x.created_at),label(x.status),money(x.amount||x.net_amount),x.production_id||'—',x.public_id||x.id])}/></section>
    {selected&&<div className="finance-modal" onClick={()=>setSelected(null)}><article onClick={e=>e.stopPropagation()}><header><div><small>TRANSAÇÃO #{selected.id}</small><h3>{money(selected.gross_amount)}</h3></div><button onClick={()=>setSelected(null)}>×</button></header><dl>{Object.entries(selected).filter(([k])=>!['metadata'].includes(k)).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v??'—')}</dd></div>)}</dl><h4>Metadata</h4><pre>{typeof selected.metadata==='string'?selected.metadata:JSON.stringify(selected.metadata,null,2)}</pre></article></div>}
  </div>
}
function Kpi({title,value,sub,danger}){return <article className={`finance-kpi ${danger?'danger':''}`}><span>{title}</span><strong>{value}</strong><small>{sub}</small></article>}
function Table({heads,rows=[]}){return <div className="finance-table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows?.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Sem dados no período.</td></tr>}</tbody></table></div>}
