export const organizationSeo = {
  name: 'Peter Tecnet',
  legalName: 'Peter Tecnet',
  url: 'https://petertecnet.com.br/',
  logo: 'https://petertecnet.com.br/petertecnet-logo-circular.jpg',
  taxID: '42.595.409/0001-48',
  email: 'contato@petertecnet.com.br',
  instagram: 'https://www.instagram.com/petertecnet/',
  description: 'A Peter Tecnet é uma empresa de tecnologia que cria e opera um ecossistema de plataformas digitais próprias, além de desenvolver software, APIs, automações, integrações e soluções sob medida para empresas.',
}

export const platformSeoEntities = {
  plat: {
    name: 'Plat',
    domain: 'https://plat.petertecnet.com.br/',
    category: 'BusinessApplication',
    eyebrow: 'Gestão digital para estabelecimentos',
    title: 'Plat | Gestão de estabelecimentos, equipe, itens e operação | Peter Tecnet',
    description: 'A Plat é uma plataforma própria da Peter Tecnet para digitalizar a gestão de estabelecimentos, centralizando empresa, equipe, itens, presença pública e rotinas operacionais em um só ambiente.',
    headline: 'Plat é a plataforma Peter Tecnet para organizar e digitalizar a operação de estabelecimentos.',
    intents: ['sistema para estabelecimentos', 'gestão de bares e restaurantes', 'gestão digital de empresa', 'sistema para operação comercial'],
    benefits: [
      'Cadastro e gestão do estabelecimento em uma estrutura digital centralizada.',
      'Organização de equipe, itens e informações operacionais.',
      'Página pública do estabelecimento para presença e descoberta online.',
      'Integração com a API central e outros produtos do ecossistema Peter Tecnet.',
    ],
    faq: [
      ['O que é a Plat da Peter Tecnet?', 'A Plat é uma plataforma própria da Peter Tecnet voltada à gestão digital de estabelecimentos e suas operações.'],
      ['A Plat é um serviço de desenvolvimento sob medida?', 'Não. A Plat é um produto do ecossistema Peter Tecnet. A empresa também oferece desenvolvimento sob medida separadamente.'],
      ['Para quais negócios a Plat pode servir?', 'A arquitetura é voltada a estabelecimentos e pode atender operações como bares, restaurantes e outros negócios que precisam organizar equipe, itens e presença digital.'],
    ],
  },
  rasoio: {
    name: 'Rasoio',
    domain: 'https://rasoio.petertecnet.com.br/',
    category: 'BusinessApplication',
    eyebrow: 'Agenda e serviços',
    title: 'Rasoio | Agendamento online para empresas de serviços | Peter Tecnet',
    description: 'Rasoio é a plataforma de agendamento online da Peter Tecnet para empresas de serviços organizarem horários, profissionais, disponibilidade, clientes e reservas.',
    headline: 'Rasoio transforma serviços, equipe e disponibilidade em uma agenda online clara para a empresa e para o cliente.',
    intents: ['agendamento online', 'agenda para empresas', 'sistema de agendamento', 'agenda para serviços'],
    benefits: [
      'Organização de serviços, profissionais e recursos agendáveis.',
      'Disponibilidade centralizada para reduzir conflitos de horário.',
      'Experiência digital para clientes encontrarem e reservarem serviços.',
      'Estrutura adaptável a diferentes segmentos que trabalham com hora marcada.',
    ],
  },
  cutinapp: {
    name: 'Cutinapp',
    domain: 'https://cutinapp.petertecnet.com.br/',
    category: 'BusinessApplication',
    eyebrow: 'Eventos, ingressos e experiências',
    title: 'Cutinapp | Eventos, ingressos, vendas e check-in por QR Code | Peter Tecnet',
    description: 'Cutinapp é a plataforma de eventos da Peter Tecnet para produtores publicarem eventos, venderem ingressos e itens, organizarem participantes e promoters e validarem entradas por QR Code.',
    headline: 'Cutinapp conecta divulgação, venda de ingressos, itens, participantes e check-in em uma única experiência de eventos.',
    intents: ['plataforma de eventos', 'venda de ingressos online', 'check-in QR Code', 'sistema para produtor de eventos'],
    benefits: [
      'Publicação e descoberta de eventos.',
      'Venda de ingressos e itens em fluxo digital integrado.',
      'Participantes, promoters e operação de acesso organizados no mesmo ecossistema.',
      'Validação de entrada com QR Code.',
    ],
  },
  nexus: {
    name: 'Nexus',
    domain: 'https://nexus.petertecnet.com.br/',
    category: 'BusinessApplication',
    eyebrow: 'Catálogo digital e presença online',
    title: 'Nexus | Catálogo digital, produtos, serviços e presença online | Peter Tecnet',
    description: 'Nexus é a plataforma de catálogo digital da Peter Tecnet para empresas publicarem produtos e serviços, criarem páginas públicas e compartilharem itens por links e QR Codes.',
    headline: 'Nexus transforma o catálogo da empresa em páginas públicas preparadas para descoberta, compartilhamento e venda.',
    intents: ['catálogo digital para empresas', 'vitrine online', 'QR Code de produto', 'página pública de produto'],
    benefits: [
      'Catálogo público organizado por estabelecimento, categorias e itens.',
      'Páginas individuais para produtos e serviços.',
      'Links e QR Codes para descoberta e compartilhamento.',
      'Integração com a API central Peter Tecnet.',
    ],
  },
  payflow: {
    name: 'PayFlow',
    domain: 'https://payflow.petertecnet.com.br/',
    category: 'BusinessApplication',
    eyebrow: 'Atendimento, vendas e cobrança',
    title: 'PayFlow | CRM, propostas, cobranças e follow-up | Peter Tecnet',
    description: 'PayFlow é a plataforma comercial da Peter Tecnet para organizar clientes, oportunidades, propostas, cobranças e follow-up em um fluxo contínuo de vendas.',
    headline: 'PayFlow organiza o caminho do primeiro contato até a cobrança paga para reduzir oportunidades esquecidas.',
    intents: ['CRM para pequenas empresas', 'pipeline de vendas', 'propostas e cobranças', 'follow-up comercial'],
    benefits: [
      'Clientes e oportunidades organizados em pipeline.',
      'Propostas e cobranças conectadas à negociação.',
      'Follow-up para reduzir vendas perdidas por falta de acompanhamento.',
      'Visibilidade do que avançou, está parado ou precisa de ação.',
    ],
  },
  laora: {
    name: 'Laora',
    domain: 'https://laora.petertecnet.com.br/',
    category: 'LifestyleApplication',
    eyebrow: 'Conexões e comunidade',
    title: 'Laora | Descoberta, conexões, matches e conversas | Peter Tecnet',
    description: 'Laora é uma plataforma própria da Peter Tecnet para descoberta de pessoas, conexões, matches e conversas, com recursos voltados à experiência social e segurança.',
    headline: 'Laora cria uma experiência digital para descoberta, conexão e relacionamento entre pessoas.',
    intents: ['aplicativo de relacionamento', 'plataforma de conexões', 'matches e conversas'],
    benefits: [
      'Descoberta de perfis e novas conexões.',
      'Matches e conversas integrados.',
      'Recursos de segurança, bloqueio e denúncia.',
      'Infraestrutura conectada ao ecossistema Peter Tecnet.',
    ],
  },
  locaio: {
    name: 'Locaio',
    domain: 'https://locaio.petertecnet.com.br/',
    category: 'BusinessApplication',
    eyebrow: 'Serviços locais e agendamentos',
    title: 'Locaio | Serviços locais, descoberta e agendamentos | Peter Tecnet',
    description: 'Locaio é uma plataforma própria da Peter Tecnet voltada à descoberta de serviços locais e à conexão entre clientes, prestadores e experiências de agendamento.',
    headline: 'Locaio aproxima quem procura um serviço de quem pode realizá-lo, com presença digital e agendamento.',
    intents: ['serviços perto de mim', 'prestadores de serviço', 'agendamento de serviços locais'],
    benefits: [
      'Descoberta de serviços e prestadores.',
      'Presença digital para negócios locais.',
      'Fluxos de contato e agendamento.',
      'Integração com capacidades compartilhadas do ecossistema.',
    ],
  },
  kryvion: {
    name: 'Kryvion',
    domain: 'https://kryvion.petertecnet.com.br/',
    category: 'FinanceApplication',
    eyebrow: 'Inteligência para mercado cripto',
    title: 'Kryvion | Análise, monitoramento e inteligência para criptomoedas | Peter Tecnet',
    description: 'Kryvion é a plataforma da Peter Tecnet para acompanhar o mercado de criptomoedas com dados, monitoramento, análises, alertas e contexto para apoiar decisões informadas.',
    headline: 'Kryvion transforma dados do mercado cripto em monitoramento, análises e alertas com mais contexto.',
    intents: ['análise de criptomoedas', 'monitoramento cripto', 'alerta de criptomoedas', 'inteligência de mercado cripto'],
    benefits: [
      'Monitoramento de ativos e movimentos relevantes.',
      'Análises com contexto e dados de mercado.',
      'Alertas e notificações para acompanhar mudanças importantes.',
      'Histórico e detalhamento para apoiar decisões com mais informação.',
    ],
    disclaimer: 'Conteúdo informativo. Não constitui recomendação de investimento nem promessa de retorno.',
  },
}

export const commercialSeoArticles = [
  {
    slug: 'sistema-para-bares-restaurantes-e-estabelecimentos',
    title: 'Sistema para bares, restaurantes e estabelecimentos: o que centralizar primeiro',
    seoTitle: 'Sistema para bares, restaurantes e estabelecimentos | Plat Peter Tecnet',
    description: 'Veja como organizar estabelecimento, equipe, itens, presença pública e rotinas digitais em uma estrutura centralizada com a Plat Peter Tecnet.',
    category: 'Gestão de estabelecimentos',
    date: '2026-09-10',
    readTime: '7 min',
    relatedPlatform: 'plat',
    intro: 'Quando cadastro da empresa, equipe, itens e informações públicas ficam espalhados, o negócio perde tempo e consistência. A Plat organiza esses elementos em uma base digital comum.',
    sections: [
      { heading: 'Comece pelo cadastro central do estabelecimento', paragraphs: ['Dados básicos, identidade, equipe e informações operacionais precisam ter uma fonte principal. Isso reduz divergências e facilita o uso das mesmas informações em páginas públicas e fluxos internos.', 'A Plat foi criada como produto próprio da Peter Tecnet para atender esse tipo de organização de estabelecimentos.'] },
      { heading: 'Itens e presença pública precisam conversar', paragraphs: ['Produtos, serviços e informações do negócio ganham mais valor quando podem ser reaproveitados em páginas públicas e outros pontos do ecossistema.', 'Esse vínculo ajuda a transformar cadastro operacional em presença digital útil para clientes.'] },
      { heading: 'Uma plataforma pronta é diferente de software sob medida', paragraphs: ['A Plat é um produto Peter Tecnet. Ela não deve ser confundida com o serviço separado de desenvolvimento de sistemas personalizados oferecido pela empresa.', 'Quando a necessidade cabe no produto, a empresa pode adotar a plataforma. Quando não cabe, a Peter Tecnet também pode desenvolver uma solução específica.'] },
    ],
  },
  {
    slug: 'agendamento-online-para-empresas-de-servicos',
    title: 'Agendamento online para empresas de serviços: como reduzir conflitos e facilitar reservas',
    seoTitle: 'Agendamento online para empresas de serviços | Rasoio Peter Tecnet',
    description: 'Entenda como organizar serviços, profissionais, horários e disponibilidade e conheça o Rasoio, plataforma de agendamento online da Peter Tecnet.',
    category: 'Agendamento',
    date: '2026-09-10',
    readTime: '7 min',
    relatedPlatform: 'rasoio',
    intro: 'Uma agenda digital eficiente precisa representar serviços, profissionais e disponibilidade de forma clara, evitando conflitos e facilitando a reserva pelo cliente.',
    sections: [
      { heading: 'Disponibilidade precisa ser uma regra do sistema', paragraphs: ['Quando horários dependem apenas de mensagens e conferência manual, conflitos ficam mais prováveis.', 'O Rasoio centraliza serviços, profissionais e disponibilidade para tornar o processo de agendamento mais previsível.'] },
      { heading: 'O cliente precisa conseguir reservar sem atrito', paragraphs: ['Uma experiência pública de agendamento reduz a quantidade de mensagens necessárias para descobrir horários e serviços.', 'A página precisa funcionar bem no celular e mostrar somente opções realmente disponíveis.'] },
      { heading: 'O Rasoio é um produto Peter Tecnet', paragraphs: ['Rasoio é uma plataforma própria do ecossistema Peter Tecnet, não uma descrição genérica de serviços de desenvolvimento.', 'Sua proposta é atender empresas que trabalham com hora marcada e precisam organizar agenda e equipe.'] },
    ],
  },
  {
    slug: 'plataforma-para-vender-ingressos-online',
    title: 'Plataforma para vender ingressos online: do evento ao check-in por QR Code',
    seoTitle: 'Plataforma para vender ingressos online | Cutinapp Peter Tecnet',
    description: 'Veja como organizar eventos, lotes, vendas, participantes, itens e check-in com QR Code usando uma operação digital integrada como a Cutinapp.',
    category: 'Eventos e ingressos',
    date: '2026-09-10',
    readTime: '8 min',
    relatedPlatform: 'cutinapp',
    intro: 'Vender ingresso não termina no pagamento. A operação precisa conectar divulgação, evento, ingresso, participante, itens adicionais e validação de entrada.',
    sections: [
      { heading: 'O fluxo precisa começar no evento e terminar no check-in', paragraphs: ['Uma plataforma de eventos deve manter o vínculo entre evento, ingresso, pagamento, QR Code e entrada validada.', 'Isso reduz etapas manuais e facilita acompanhar a jornada do participante.'] },
      { heading: 'Itens adicionais aumentam a utilidade do checkout', paragraphs: ['Quando o evento vende também produtos ou itens de consumo, um carrinho integrado evita cobranças separadas desnecessárias.', 'O objetivo é manter uma experiência de compra simples e transparente.'] },
      { heading: 'Cutinapp é a plataforma de eventos da Peter Tecnet', paragraphs: ['A Cutinapp é um produto próprio criado para produtores, participantes, artistas e promoters.', 'Sua identidade precisa ser reconhecida por buscadores como uma plataforma específica do ecossistema Peter Tecnet.'] },
    ],
  },
  {
    slug: 'crm-para-pequenas-empresas-follow-up-propostas-cobrancas',
    title: 'CRM para pequenas empresas: como organizar follow-up, propostas e cobranças',
    seoTitle: 'CRM para pequenas empresas, propostas e cobranças | PayFlow Peter Tecnet',
    description: 'Organize clientes, oportunidades, propostas, cobranças e follow-up em um fluxo comercial contínuo com o PayFlow da Peter Tecnet.',
    category: 'Vendas',
    date: '2026-09-10',
    readTime: '7 min',
    relatedPlatform: 'payflow',
    intro: 'Muitas vendas são perdidas porque o próximo passo fica esquecido. Um CRM simples precisa deixar claro quem é o cliente, qual oportunidade está aberta e o que deve acontecer em seguida.',
    sections: [
      { heading: 'Pipeline sem próximo passo vira apenas uma lista', paragraphs: ['Cada oportunidade precisa ter estado, histórico e uma ação seguinte.', 'O PayFlow conecta atendimento, proposta, cobrança e follow-up para que a operação comercial continue avançando.'] },
      { heading: 'Proposta e cobrança fazem parte da mesma venda', paragraphs: ['Separar completamente negociação, proposta e cobrança cria lacunas de informação.', 'Um fluxo integrado facilita entender o que já foi enviado, aceito, cobrado e pago.'] },
      { heading: 'PayFlow é um produto do ecossistema Peter Tecnet', paragraphs: ['PayFlow é uma plataforma própria da Peter Tecnet voltada ao processo comercial.', 'Ela complementa outros produtos do ecossistema sem confundir sua função com desenvolvimento de software sob medida.'] },
    ],
  },
]

export const legacyRedirects = {
  '/solucoes/desenvolvimento-de-apis': '/servicos/apis-e-integracoes',
  '/solucoes/desenvolvimento-de-api': '/servicos/apis-e-integracoes',
  '/blog/agendamento-online-para-empresas-de-servicos': '/blog/agendamento-online-para-empresas-de-servicos',
}
